### ISSUE TITLE
R Optimizer

### ISSUE THREAD

**Issue by gfuzz** [daviesb/DFS-Optimizer#1]
I was hoping to expand on this using my own data, but am unable to get R optimizer working...... Not really posting an issue, rather reaching out to see if I can get some input. Great work. I appreciate the time it must have taken to code this. Love the concept, and stumbled across this trying to find exactly this. Lets talk!

**Comment by daviesb** [comment]
Happy to help out - what is the error that you're running into with the optimizer?
